apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-code-app
  annotations:
    github.com/project-slug: aravindavvaru/python-code-app
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/template.yaml
spec:
  type: service
  lifecycle: experimental
  owner: guests
